### PR TITLE
Adding support for HACS

### PR DESCRIPTION
**Pull request by troykelly**
Will need to be compliant with the [HACS rules](https://hacs.xyz/docs/publish/include/#check-repository) before listing - but at least people can use HACS to install from the repo.

### CODE REVIEW

**Comment by bjeanes** [comment]
Huh weird. I was able to install it with HACS prior to this (after adding this repo to HACS as a custom repo). Do I have to do anything special to switch to the official HACS distribution?

**Comment by madpilot** [comment]
No idea - I've never used HACS. @troykelly ?

**Comment by troykelly** [comment]
tl;dr You shouldn't need to change anything @bjeanes 

longer version: Once I get a chance to fix the missing brand, @madpilot can request listing in HACS to make it easier (or not - totally up to them!)
HACS's "listed" repositories are really just references to the repos so you don't have to add them manually.
I'm surprised you could just add the repo without the [hacs.json](https://github.com/madpilot/hass-amber-electric/blob/master/hacs.json) - maybe custom repo's are a little more forgiving?

**Comment by madpilot** [comment]
The brand stuff is fixed. Last error is "The repository is missing topics" - https://github.com/madpilot/hass-amber-electric/runs/3067287117

**Comment by troykelly** [comment]
> The brand stuff is fixed. Last error is "The repository is missing topics" - https://github.com/madpilot/hass-amber-electric/runs/3067287117 - which I don't know how to fix

That one is tucked away [here](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/classifying-your-repository-with-topics). You sort of need a Rosetta Stone to work out some HA stuff.

**Comment by madpilot** [comment]
Ok, we are green: https://github.com/madpilot/hass-amber-electric/runs/3074022114

How do I request a HACs listing?

**Comment by troykelly** [comment]
I had to remove mine, so I've added yours [here](https://github.com/hacs/default/pull/1022).
If it gets rejected for trying to do two things at once - the instructions are [here](https://hacs.xyz/docs/publish/include).

**Comment by madpilot** [comment]
Cool - can't do it now, will try tonight or in the morning

**Comment by troykelly** [comment]
Turns out I can't do it - I'm [not a major contributor](https://github.com/hacs/default/pull/1022/checks?check_run_id=3074174513)
`Error: 'troykelly' is not a major contributor to 'madpilot/hass-amber-electric'`

You will need to add to the appropriate spot in [integration](https://github.com/hacs/default/blob/master/integration)
```
  "madpilot/hass-amber-electric",
```

**Comment by madpilot** [comment]
Done. Waiting for approval

**Pull request merged**
